Headers = 1*(Header CRLF) CRLF

Headers-Loose = 1*(Header [CR] LF) [CR] LF

Header
  = "Accept" COWS Accept
  / "Accept-CH" COWS Accept-CH
  / "Accept-Charset" COWS Accept-Charset
  / "Accept-Encoding" COWS Accept-Encoding
  / "Accept-Language" COWS Accept-Language
  / "Accept-Ranges" COWS Accept-Ranges
  / "Age" COWS Age
  / "Allow" COWS Allow
  / "ALPN" COWS ALPN
  / "Alt-Svc" COWS Alt-Svc
  / "Authentication-Info" COWS Authentication-Info
  / "Authorization" COWS Authorization
  / "Cache-Control" COWS Cache-Control
  / "Connection" COWS Connection
  / "Content-Encoding" COWS Content-Encoding
  / "Content-Language" COWS Content-Language
  / "Content-Length" COWS Content-Length
  / "Content-Location" COWS Content-Location
  / "Content-Range" COWS Content-Range
  / "Content-Security-Policy" COWS Content-Security-Policy
  / "Content-Security-Policy-Report-Only" COWS Content-Security-Policy-Report-Only
  / "Content-Type" COWS Content-Type
  / "Cross-Origin-Resource-Policy" COWS Cross-Origin-Resource-Policy
  / "Date" COWS Date
  / "ETag" COWS ETag
  / "Expect" COWS Expect
  / "Expires" COWS Expires
  / "From" COWS From
  / "Host" COWS Host
  / "If-Match" COWS If-Match
  / "If-Modified-Since" COWS If-Modified-Since
  / "If-None-Match" COWS If-None-Match
  / "If-Range" COWS If-Range
  / "If-Unmodified-Since" COWS If-Unmodified-Since
  / "IMF-fixdate" COWS IMF-fixdate
  / "Last-Modified" COWS Last-Modified
  / "Location" COWS Location
  / "Max-Forwards" COWS Max-Forwards
  / "NEL" COWS NEL
  / "Permissions-Policy" COWS Permissions-Policy
  / "Proxy-Authenticate" COWS Proxy-Authenticate
  / "Proxy-Authentication-Info" COWS Proxy-Authentication-Info
  / "Proxy-Authorization" COWS Proxy-Authorization
  / "Range" COWS Range
  / "Referer" COWS Referer
  / "Referrer-Policy" COWS Referrer-Policy
  / "Retry-After" COWS Retry-After
  / "Server-Timing" COWS Server-Timing
  / "Server" COWS Server
  / "Set-Cookie" COWS set-cookie-string
  / "Strict-Transport-Security" COWS Strict-Transport-Security
  / "TE" COWS TE
  / "Trailer" COWS Trailer
  / "Upgrade" COWS Upgrade
  / "User-Agent" COWS User-Agent
  / "Vary" COWS Vary
  / "Via" COWS Via
  / "WWW-Authenticate" COWS WWW-Authenticate
  / Unknown-Header

Unknown-Header = field-name COWS field-content

COWS = %s":" OWS

